services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hammers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 hammer_test.wsgi:application"
    volumes:
      -  .:/app
    ports:
      - "8000:8000"